export enum EnumTransport {
  car = "car",
  motorcyle = "motorcycle",
  truck = "truck",
}

export enum InteriorOption {
  markedInterior = "marked Interior",
  autonomousHeating = "autonomous Heating",
  electricallyAdjustableSeats = "electrically Adjustable Seats",
  leatherInterior = "leather Interior",
  heatedSeats = "heated Seats",
  trunkCover = "trunk Cover",
  electricallyAdjustableSeatsWithMemory = "electrically Adjustable Seats With Memory",
  airConditioning = "air Conditioning",
  tintedWindows = "tinted Windows",
  multifunctionalSteeringWheel = "multifunctional Steering Wheel",
  climateControl = "climate Control",
  sportsSeats = "sports Seats",
  velourInterior = "velour Interior",
  powerWindows = "power Windows",
  massageSeats = "massage Seats",
  heatedSteeringWheel = "heated Steering Wheel",
  ventilatedSeats = "ventilated Seats",
  other = "other",
}

export enum ExteriorOption {
  automaticallyFoldingMirrors = "automatically Folding Mirrors",
  LEDLights = "LED Lights",
  frontHeadlightWasher = "front Headlight Washer",
  summerTireSet = "summer Tire Set",
  doorClosingAssist = "door Closing Assist",
  alloyWheels = "alloy Wheels",
  fogLights = "fog Lights",
  xenonLights = "xenon Lights",
  towHook = "tow Hook",
  matrixLights = "matrix Lights",
  sunroof = "sunroof",
  winterTireSet = "winter Tire Set",
  LEDDaytimeRunningLights = "LED Daytime Running Lights",
  panoramicRoof = "panoramic Roof",
  roofRackMounts = "roof Rack Mounts",
  other = "other",
}

export enum ElectronicsOption {
  distanceSensingSystem = "distance Sensing System",
  electricallyAdjustableMirrors = "electrically Adjustable Mirrors",
  LCDscreen = "LCD screen",
  headsUpDisplay = "heads-Up Display",
  automaticallyTurningLights = "automatically Turning Lights",
  electricallyAdjustableSteeringColumn = "electrically Adjustable Steering Column",
  touchScreen = "touch Screen",
  digitalDashboard = "digital Dashboard",
  autopilot = "autopilot",
  electricallyHeatedFrontWindshield = "electrically Heated Front Windshield",
  navigationGPS = "navigation GPS",
  startStopSystem = "start-Stop System",
  keylessStartSystem = "keyless Start System",
  electricallyOperatedTrunkLid = "electrically Operated Trunk Lid",
  paddleShifters = "paddle Shifters",
  heatedMirrors = "heated Mirrors",
  wirelessPhoneCharging = "wireless Phone Charging",
  rainSensor = "rain Sensor",
  dimmingMirror = "dimming Mirror",
  voiceControl = "voice Control",
}

export enum SafetySecurityOption {
  viewCamera360 = "view Camera 360",
  ESP = "ESP",
  nightVisionAssistant = "night Vision Assistant",
  frontViewCamera = "front View Camera",
  blindSpotMonitoringSystem = "blind Spot Monitoring System",
  rearViewCamera = "rear View Camera",
  fatigueWarningSystem = "fatigue Warning System",
  alarmImmobilizer = "alarm Immobilizer",
  distanceKeepingSystem = "distance Keeping System",
  hillDescentControl = "hill Descent Control",
  airbags = "airbags",
  collisionPreventionSystem = "collision Prevention System",
  automaticParkingSystem = "automatic Parking System",
  ISOFIX = "ISOFIX",
  tirePressureMonitoringSystem = "tire Pressure Monitoring System",
  distantLightsAssistant = "distant Lights Assistant",
  emergencyBrakingSystem = "emergency Braking System",
  laneKeepingSystem = "lane Keeping System",
  emergencyCallSystem = "emergency Call System",
  tractionControlSystem = "traction Control System",
  dynamicCorneringLights = "dynamic Cornering Lights",
  roadSignRecognitionSystem = "road Sign Recognition System",
  satelliteTrackingSystem = "satellite Tracking System",
}

export enum AudioVideoOption {
  appleCarPlayAndroidAuto = "apple CarPlay Android Auto",
  CDPlayer = "CD Player",
  handsFreeEquipment = "hands-Free Equipment",
  USBConnection = "USB Connection",
  audioPlayer = "audio Player",
  CDChanger = "CD Changer",
  MP3Player = "MP3 Player",
  USBTypeCConnection = "USB Type C Connection",
  AUXConnection = "AUX Connection",
  DVDPlayer = "DVD Player",
  additionalAudioEquipment = "additional Audio Equipment",
  subwoofer = "subwoofer",
  Bluetooth = "Bluetooth",
  HiFiaudioSystem = "Hi-Fi audio System",
  TVScreen = "TV Screen",
}

export enum OtherOption {
  carFromAmerica = "car From America",
  notExploitedInLithuania = "not Exploited In Lithuania",
  availableForLeasing = "available For Leasing",
  adaptedForDisabled = "adapted For Disabled",
  warranty = "warranty",
  increasedEnginePower = "increased Engine Power",
  readyForMotorsport = "ready For Motorsport",
  serviceBook = "service Book",
  multipleSetsOfKeys = "multiple Sets Of Keys",
}

export enum MotoFeatures {
  wheelDrive_4x4 = "4x4",
  cruiseControl = "cruise control",
  heatedSeats = "heated seats",
  passengersBackrest = "passengers back rest",
  abs = "abs",
  damper = "damper",
  keylessEngineStart = "keyless engine start",
  tractionControlSystem = "traction control system",
  alarmImmobilizer = "alarm / immobilizer",
  discBrakes = "disc brakes",
  lease = "lease",
  travelBags = "travel bags",
  audioEquipment = "audio equipment",
  electricStarter = "electric starter",
  ledDaytimeRunningLights = "LED daytime running lights",
  warranty = "warranty",
  automaticTransmission = "automatic transmission",
  flatRearWheel = "flat rear wheel",
  navigationGPS = "navigation / GPS",
  windshield = "windshield",
  cradle = "cradle",
  heatedHandles = "heated handles",
  notExploitedInLithuania = "not exploited in Lithuania",
  withDocuments = "with documents",
}
