export enum EnumTransport {
  car = "car",
  motorcyle = "motorcyle",
  truck = "truck",
}

export enum InteriorOption {
  markedInterior = "markedInterior",
  autonomousHeating = "autonomousHeating",
  electricallyAdjustableSeats = "electricallyAdjustableSeats",
  leatherInterior = "leatherInterior",
  heatedSeats = "heatedSeats",
  trunkCover = "trunkCover",
  electricallyAdjustableSeatsWithMemory = "electricallyAdjustableSeatsWithMemory",
  airConditioning = "airConditioning",
  tintedWindows = "tintedWindows",
  multifunctionalSteeringWheel = "multifunctionalSteeringWheel",
  climateControl = "climateControl",
  sportsSeats = "sportsSeats",
  velourInterior = "velourInterior",
  powerWindows = "powerWindows",
  massageSeats = "massageSeats",
  heatedSteeringWheel = "heatedSteeringWheel",
  ventilatedSeats = "ventilatedSeats",
  other = "other",
}

export enum ExteriorOption {
  automaticallyFoldingMirrors = "automaticallyFoldingMirrors",
  LEDLights = "LEDLights",
  frontHeadlightWasher = "frontHeadlightWasher",
  summerTireSet = "summerTireSet",
  doorClosingAssist = "doorClosingAssist",
  alloyWheels = "alloyWheels",
  fogLights = "fogLights",
  xenonLights = "xenonLights",
  towHook = "towHook",
  matrixLights = "matrixLights",
  sunroof = "sunroof",
  winterTireSet = "winterTireSet",
  LEDDaytimeRunningLights = "LEDDaytimeRunningLights",
  panoramicRoof = "panoramicRoof",
  roofRackMounts = "roofRackMounts",
  other = "other",
}

export enum ElectronicsOption {
  distanceSensingSystem = "distanceSensingSystem",
  electricallyAdjustableMirrors = "electricallyAdjustableMirrors",
  LCDscreen = "LCDscreen",
  headsUpDisplay = "headsUpDisplay",
  automaticallyTurningLights = "automaticallyTurningLights",
  electricallyAdjustableSteeringColumn = "electricallyAdjustableSteeringColumn",
  touchScreen = "touchScreen",
  digitalDashboard = "digitalDashboard",
  autopilot = "autopilot",
  electricallyHeatedFrontWindshield = "electricallyHeatedFrontWindshield",
  navigationGPS = "navigationGPS",
  startStopSystem = "startStopSystem",
  keylessStartSystem = "keylessStartSystem",
  electricallyOperatedTrunkLid = "electricallyOperatedTrunkLid",
  paddleShifters = "paddleShifters",
  heatedMirrors = "heatedMirrors",
  wirelessPhoneCharging = "wirelessPhoneCharging",
  rainSensor = "rainSensor",
  dimmingMirror = "dimmingMirror",
  voiceControl = "voiceControl",
}

export enum SafetySecurityOption {
  viewCamera360 = "viewCamera360",
  ESP = "ESP",
  nightVisionAssistant = "nightVisionAssistant",
  frontViewCamera = "frontViewCamera",
  blindSpotMonitoringSystem = "blindSpotMonitoringSystem",
  rearViewCamera = "rearViewCamera",
  fatigueWarningSystem = "fatigueWarningSystem",
  alarmImmobilizer = "alarmImmobilizer",
  distanceKeepingSystem = "distanceKeepingSystem",
  hillDescentControl = "hillDescentControl",
  airbags = "airbags",
  collisionPreventionSystem = "collisionPreventionSystem",
  automaticParkingSystem = "automaticParkingSystem",
  ISOFIX = "ISOFIX",
  tirePressureMonitoringSystem = "tirePressureMonitoringSystem",
  distantLightsAssistant = "distantLightsAssistant",
  emergencyBrakingSystem = "emergencyBrakingSystem",
  laneKeepingSystem = "laneKeepingSystem",
  emergencyCallSystem = "emergencyCallSystem",
  tractionControlSystem = "tractionControlSystem",
  dynamicCorneringLights = "dynamicCorneringLights",
  roadSignRecognitionSystem = "roadSignRecognitionSystem",
  satelliteTrackingSystem = "satelliteTrackingSystem",
}

export enum AudioVideoOption {
  appleCarPlayAndroidAuto = "appleCarPlayAndroidAuto",
  CDPlayer = "CDPlayer",
  handsFreeEquipment = "handsFreeEquipment",
  USBConnection = "USBConnection",
  audioPlayer = "audioPlayer",
  CDChanger = "CDChanger",
  MP3Player = "MP3Player",
  USBTypeCConnection = "USBTypeCConnection",
  AUXConnection = "AUXConnection",
  DVDPlayer = "DVDPlayer",
  additionalAudioEquipment = "additionalAudioEquipment",
  subwoofer = "subwoofer",
  Bluetooth = "Bluetooth",
  HiFiaudioSystem = "HiFiaudioSystem",
  TVScreen = "TVScreen",
}

export enum OtherOption {
  carFromAmerica = "carFromAmerica",
  notExploitedInLithuania = "notExploitedInLithuania",
  availableForLeasing = "availableForLeasing",
  adaptedForDisabled = "adaptedForDisabled",
  warranty = "warranty",
  increasedEnginePower = "increasedEnginePower",
  readyForMotorsport = "readyForMotorsport",
  serviceBook = "serviceBook",
  multipleSetsOfKeys = "multipleSetsOfKeys",
}
